name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (quietly)
        run: npm ci --silent > /dev/null 2>&1

      - name: Install Playwright Browsers (quietly)
        run: npx playwright install --with-deps > /dev/null 2>&1

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Upload Playwright HTML Report (always)
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report
