name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --silent > /dev/null 2>&1

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps > /dev/null 2>&1

      - name: Run tests and generate HTML report
        run: npx playwright test --reporter=html

      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
