name: Playwright Tests & Deploy Report

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --silent > /dev/null 2>&1

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps > /dev/null 2>&1

      - name: Run Playwright tests
        run: npx playwright test --reporter=html || true

      # Copy report to public folder for GitHub Pages
      - name: Copy Playwright Report to public folder
        run: |
          mkdir -p public
          cp -R playwright-report/* public/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
